name: Output information
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github Issue Context
              run: echo "${{ toJSON(github.event.issue) }}"